package com.maioshaproject.dao;

import com.maioshaproject.dataObject.OrderDO;

public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Aug 21 15:42:27 CST 2019
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Aug 21 15:42:27 CST 2019
     */
    int insertSelective(OrderDO record);

}