package com.maioshaproject.dao;

import com.maioshaproject.dataObject.UserPasswordDO;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Aug 12 18:35:25 CST 2019
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Aug 12 18:35:25 CST 2019
     */
    int insertSelective(UserPasswordDO record);
}